### ISSUE TITLE
mnk-2 Indexes

### ISSUE THREAD

**Issue by decaruju** [decaruju/munk#2]
A field you be indexable, and give constant-time lookup. Indexes are stored in a new field in the db.json file under 'indexes'.
The proposed syntax is
```
User:
  name:
    type: str
    index: true
```
