### ISSUE TITLE
mnk-3 Reference type

### ISSUE THREAD

**Issue by decaruju** [decaruju/munk#3]
A field should be able to have a reference type, referencing another object using the following syntax:
```
---
User:
  name:
    type: str
    required: true
    index: true
  orders:
    type: reference Order 

Order:
  date:
    type: datetime
  products:
    type: reference Product 
  buyer:
    type: reference User 

Product:
  name:
    type: str
...
```
